#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

#REMOVEME? ynh_nodejs_install

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Local-first personal finance tool" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# INSTALL ACTUAL
#=================================================
if ynh_app_upgrading_from_version_before 25.6.1~ynh1; then
       ynh_safe_rm $install_dir
fi

ynh_script_progression "Installing $app..."

mkdir -p $install_dir
pushd $install_dir
	ynh_hide_warnings npm install @actual-app/sync-server@$(ynh_app_upstream_version)
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Listening on" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
